### ISSUE TITLE
Cant use in lockscreen / Rotation feature

### ISSUE THREAD

**Issue by Snikkard** [leon47331/scriptable-news-rss-widget#1]
Hi. Great thing to use. 
But you can only choose Scriptable as home screen widget, not lock screen. It doesnt show up in the menu to choose. 

Also, could I add more news titles than just the one ? Id like to see maybe the latest 5 from the RSS feed. 
thank you

**Comment by leon47331** [comment]
Hi @Snikkard!
Thanks for posting the issue!

Have you done anything step by step like in the guide I provided?
That's weird that you don't see Scriptable on your lockscreen.

Maybe you could try to delete and re-install Scriptable?
That's sadly something where I can't help you much because I'm only a widget developer and not the app developer...


For your idea with multiple news titles:
There is not much room on the lockscreen to display more than one news article.
Maybe you mean some scrolling feature where the widget scrolls through the last 5 articles and changes every 5-10 minutes or so?

**Comment by drikkes** [comment]
Hi, thanks for sharing your widget. I like it and it's in use on my lockscreen.
I think what was suggested on Reddit is not about scrolling or showing mutiple items, but some sort of algo, which single item to show. Instead of using only the latest item published, is there a way for example to show 1 random headline from, let's say, the last 5 entries? Just to make sure (like the Reddit user suggests) that in a publishing gap the widget does not use the same headline half a day.

I'm not a coder, but I guess it would be easier to simply being able to add more than one feed to the same widget? This way chances would be minimized that the first news you see after waking up is same news as the last one you read before going to sleep.

(But I guess the search for a perfect feed is another question. I tried "tagesschau/alle-meldung", it has this problem of sometimes not publishing for hours, then at times pushing every few minutes... And it's too much Börse for me. Will try Deutschlandfunk next. Any recommendations for a feed about German-centered news without paywall are welcome – but I guess this would be more of a topic for Reddit...)

**Comment by leon47331** [comment]
@Snikkard I added the rotation feature in [#v1.1.0](https://github.com/leon47331/scriptable-lockscreen-rss-widget/releases/tag/v1.1.0)
I hope it's exactly what you requested :)

@drikkes
I am using ntv which is without a paywall and has many updates ;)
